### ISSUE TITLE
ChimeHelper does not recognize Personalized ID

### ISSUE THREAD

**Issue by abhineet-bansal** [nachmore/ChimeHelper#3]
I had a meeting which has location set as: `chime: someones_personal_id` instead of the meeting id in the digits form. Chime Helper did not recognize that meeting i.e. it didn't show up in the list of meetings.

**Comment by nachmore** [comment]
It's an interesting scenario that I played around with early on (since I have a cool short ID :P) but couldn't come up with a rock solid easy way to implement (because I of course ran into a scenario that had a sentence like "for example, in Chime: blah blah and in Some Other Software: bloo bloo").

The regex to find this is fairly simple, perhaps this would be useful just for the location field?
